### ISSUE TITLE
Hoverboard and Rasberry pi Integration

### ISSUE THREAD

**Issue by numan1702** [alex-makarov/hoverboard-driver#10]
Dear Alex Makarov and all,

I'm trying to communicate between my Hoberboard and Rasberry pi board using the Hoverboard-Driver as the ROS Package and the bipropellant-hoverboard-firmware that I flashed on the Mainboard-Hoverboard. I have tried changing the port configuration from / dev / ttyTHS1 to / dev / ttyS0 in the config.h in this ROS package. Besides that I also changed:
"#ifndef CONTROL_TYPE
   #define CONTROL_TYPE HOVERBOARD_WITH_SOFTWARE_SERIAL_B2_C9
#endif "
Becomes :
#ifndef CONTROL_TYPE
   #define CONTROL_TYPE USART2_CONTROLLED
#endif
Because I use the left sensor board for communication with the Rasberry Pi board.
However serial communication still failed. Is there still a configuration that is still lacking or incorrect?
Here is the Package that I use:

1. https://github.com/alex-makarov/hoverboard-driver 
2. https://github.com/bipropellant/bipropellant-hoverboard-firmware

Is the hbprotocol on the bipropellant-hoverboard-firmware not the same version as the Hoverboard-driver ROS package?
If so, can you include the bipropellant-hoverboard-firmware you use for the Hoverboard-driver ROS package? I see the bipropellant-hoverboard-firmware has changed. Or the ROS package can still be used even though the latest version of the bipropellant-hoverboard-firmware?

Sorry if my question is a stupid question, I'm still new to using ROS. For your attention I would like to thank.

Best Begards,
Alaek

**Comment by Spawn32** [comment]
Did you get this resolved @alaeknuman ?
I am getting the same fault on a Nvida AG Xavier, thought they had the same HW setup as the Nano and NX ?
Using the right usart on the hoverboard, so i have not changed anything in the firmware

Any idea @alex-makarov ?

EDIT: have tested both ttyTHS0 and ttyTHS1, both give the same error, "can not open serial port to hoverboard"

Regards
Spawn32

**Comment by Spawn32** [comment]
Solved it on my AGX Xavier:

needs to be     #define PORT "/dev/ttyTHS0" in "hoverboard-driver/include/hoverboard_driver/config.h"

Then you must disable the serial console:
$ systemctl stop nvgetty
$ systemctl disable nvgetty
$ udevadm trigger

And set the correct permissions for the serial port:
$ sudo chmod o+rw /dev/ttyTHS0
