### ISSUE TITLE
Firmware

### ISSUE THREAD

**Issue by quangvu16** [alex-makarov/hoverboard-driver#12]
Dear Alex,
As you mentioned in Github, you use firmware by p-h-a-i-i.
Do you adjust any parameters in the original firmware? If yes, please send me your firmware by email: vuvuvu@outlook.com.
Thank you,

**Comment by alex-makarov** [comment]
Hey @quangvu16, I'm using [bipropellant](https://github.com/bipropellant/bipropellant-hoverboard-firmware) stock firmware.

**Comment by quangvu16** [comment]
Thank you. I will try

**Comment by busbuyukefe** [comment]
> Hey @quangvu16, I'm using [bipropellant](https://github.com/bipropellant/bipropellant-hoverboard-firmware) stock firmware.

I built the firmware by uncommenting the usart2 on platformio.ini file and I get the following error repeatedly:
`Timeout reading from serial /dev/ttyAMA0 failed`
