### ISSUE TITLE
Installation Step of hoverboard_driver: https://github.com/quangvu16/hoverboard_driver

### ISSUE THREAD

**Issue by quangvu16** [alex-makarov/hoverboard-driver#13]
Dear Friends,
Alex's project is very interesting when you can use your old hoverboard to make 2 wheel ROS robot.
We took 2 months to install. We would like to make you easier.
Please follow steps in our github
https://github.com/quangvu16/hoverboard_driver
Hope you will study much during making Robaka robot.
Best regards,

**Comment by alex-makarov** [comment]
Hey @quangvu16 , 

please try again -- I've updated the submodules.

**Comment by quangvu16** [comment]
Dear @alex-makarov,
Please help me again. Thank you
1) I compiled successfully hoverboard-deriver and robaka-ros package:
ubuntu@ubuntu:~/Ros_ws$ catkin_make
Base path: /home/ubuntu/Ros_ws
Source space: /home/ubuntu/Ros_ws/src
Build space: /home/ubuntu/Ros_ws/build
Devel space: /home/ubuntu/Ros_ws/devel
Install space: /home/ubuntu/Ros_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/ubuntu/Ros_ws/build"
####
####
#### Running command: "make -j4 -l4" in "/home/ubuntu/Ros_ws/build"
####
[  9%] Built target hoverboard_driver_gencfg
[ 27%] Built target odom_listener
[100%] Built target hoverboard_driver

2) I connected wire rx hoverboard to tx jetson, tx hoverboard to rx jetson
However, there are no feedback from hoverboard. I use https://github.com/bipropellant/bipropellant-hoverboard-firmware with "default_envs = control_usart2"

When i run this code, hoverboard did not feedback information.
ubuntu@ubuntu:~/Ros_ws$ roslaunch hoverboard_driver hoverboard.launch 
... logging to /home/ubuntu/.ros/log/d04c325c-8226-11eb-bc66-28ee5206d98e/roslaunch-ubuntu-6272.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:45829/

SUMMARY
========

PARAMETERS
 * /hoverboard_joint_publisher/left_wheel: left_wheel
 * /hoverboard_joint_publisher/publish_rate: 50
 * /hoverboard_joint_publisher/right_wheel: right_wheel
 * /hoverboard_joint_publisher/type: joint_state_contr...
 * /hoverboard_velocity_controller/allow_multiple_cmd_vel_publishers: True
 * /hoverboard_velocity_controller/angular/z/has_acceleration_limits: True
 * /hoverboard_velocity_controller/angular/z/has_jerk_limits: True
 * /hoverboard_velocity_controller/angular/z/has_velocity_limits: True
 * /hoverboard_velocity_controller/angular/z/max_acceleration: 3.14
 * /hoverboard_velocity_controller/angular/z/max_jerk: 3.14
 * /hoverboard_velocity_controller/angular/z/max_velocity: 1.57
 * /hoverboard_velocity_controller/base_frame_id: base_footprint
 * /hoverboard_velocity_controller/cmd_vel_timeout: 0.5
 * /hoverboard_velocity_controller/enable_odom_tf: False
 * /hoverboard_velocity_controller/left_wheel: left_wheel
 * /hoverboard_velocity_controller/linear/x/has_acceleration_limits: True
 * /hoverboard_velocity_controller/linear/x/has_jerk_limits: True
 * /hoverboard_velocity_controller/linear/x/has_velocity_limits: True
 * /hoverboard_velocity_controller/linear/x/max_acceleration: 1.0
 * /hoverboard_velocity_controller/linear/x/max_jerk: 0.1
 * /hoverboard_velocity_controller/linear/x/max_velocity: 0.25
 * /hoverboard_velocity_controller/odom_frame_id: /raw_odom
 * /hoverboard_velocity_controller/pose_covariance_diagonal: [0.001, 0.001, 10...
 * /hoverboard_velocity_controller/publish_rate: 50.0
 * /hoverboard_velocity_controller/right_wheel: right_wheel
 * /hoverboard_velocity_controller/twist_covariance_diagonal: [0.001, 0.001, 10...
 * /hoverboard_velocity_controller/type: diff_drive_contro...
 * /hoverboard_velocity_controller/wheel_radius: 0.0825
 * /hoverboard_velocity_controller/wheel_radius_multiplier: 1.0
 * /hoverboard_velocity_controller/wheel_separation: 0.32
 * /hoverboard_velocity_controller/wheel_separation_multiplier: 1.0
 * /robaka/hardware_interface/joints: ['left_wheel', 'r...
 * /robaka/hardware_interface/loop_hz: 50
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    controller_spawner (controller_manager/spawner)
    hoverboard_driver (hoverboard_driver/hoverboard_driver)

auto-starting new master
process[master]: started with pid [6286]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d04c325c-8226-11eb-bc66-28ee5206d98e
process[rosout-1]: started with pid [6297]
started core service [/rosout]
process[hoverboard_driver-2]: started with pid [6309]
process[controller_spawner-3]: started with pid [6310]
[hoverboard_driver-2] process has died [pid 6309, exit code -11, cmd /home/ubuntu/Ros_ws/devel/lib/hoverboard_driver/hoverboard_driver __name:=hoverboard_driver __log:=/home/ubuntu/.ros/log/d04c325c-8226-11eb-bc66-28ee5206d98e/hoverboard_driver-2.log].
log file: /home/ubuntu/.ros/log/d04c325c-8226-11eb-bc66-28ee5206d98e/hoverboard_driver-2*.log
[INFO] [1615438882.255618]: Controller Spawner: Waiting for service controller_manager/load_controller
[WARN] [1615438912.518275]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[controller_spawner-3] process has finished cleanly
log file: /home/ubuntu/.ros/log/d04c325c-8226-11eb-bc66-28ee5206d98e/controller_spawner-3*.log
^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

3. I run rostopic list. There is not hoverboard_velocity_controller:
ubuntu@ubuntu:~/Ros_ws$ rostopic list
/hoverboard/battery_voltage
/hoverboard/left_wheel/cmd
/hoverboard/left_wheel/current
/hoverboard/left_wheel/eff
/hoverboard/left_wheel/position
/hoverboard/left_wheel/velocity
/hoverboard/right_wheel/cmd
/hoverboard/right_wheel/current
/hoverboard/right_wheel/eff
/hoverboard/right_wheel/position
/hoverboard/right_wheel/velocity
/rosout
/rosout_agg

**Comment by alex-makarov** [comment]
Which pins on Nano and hoverboard controller have you connected? Have you connected GND as well?

**Comment by quangvu16** [comment]
Dear Alex,
I connected Hoverboard left wire connector to Jeston Nano: TX to RX (pin 10), RX to TX (pin 8), GND to GND (pin 6).
I tried to compile many firmwares and uploaded to motherboard, but hoverboard did not reply information when I run roslaunch hoverboard-driver hoverboard.launch.
Please send me your firmware hex file.
Thank you for your support.

**Comment by alex-makarov** [comment]
I don't have a hex file, I've flashed it long time ago. I would recommend checking with something else (logic analyzer, oscilloscope or arduino board), whether hoverboard is sending anything to UART2.

**Comment by quangvu16** [comment]
Dear Alex,
Thank you very much.
With firmware's config.h, I only uncomment UART2, build and upload to hoverboard. Is it right?

include_dir = inc

;default_envs = genericSTM32F103RC
;default_envs = hoverboard
;default_envs = hoverboard_6word
;default_envs = control_softwareserial
default_envs = control_usart2
;default_envs = control_usart3
;default_envs = control_usart3_ADC
;default_envs = control_ADC
;default_envs = control_PPM

**Comment by busbuyukefe** [comment]
@alex-makarov I know it is asking for too much but is it possible for you to make a simple tutorial? When default bipropellant firmware with uart2 config flashed on hoverboard it doesn't work.

**Comment by alex-makarov** [comment]
I'll look into it.

**Comment by alex-makarov** [comment]
In the meanwhile -- my firmware is based on commit 5d296378f30891fdbd40b45df61b52666f4f4cdc from https://github.com/bipropellant/bipropellant-hoverboard-firmware/commits. I think latest FW has breaking changes in the protocol. You can try that commit. I'm also attaching my local diff against that commit below. When I have time, I'll either adapt it to the latest FW from bipropellant or make a fork:

```
diff --git a/inc/comms.h b/inc/comms.h
index 53bb7ae..b5334b2 100644
--- a/inc/comms.h
+++ b/inc/comms.h
@@ -11,7 +11,7 @@ typedef struct tag_serial_usart_buffer {
 
 } SERIAL_USART_BUFFER;
 
-#if defined(SERIAL_USART2_IT)
+#if defined(SERIAL_USART2_IT) || defined (DEBUG_SERIAL_USART2)
 
     extern volatile SERIAL_USART_BUFFER usart2_it_TXbuffer;
     extern volatile SERIAL_USART_BUFFER usart2_it_RXbuffer;
@@ -22,7 +22,7 @@ typedef struct tag_serial_usart_buffer {
 
 #endif
 
-#if defined(SERIAL_USART3_IT)
+#if defined(SERIAL_USART3_IT) || defined (DEBUG_SERIAL_USART3)
 
     extern volatile SERIAL_USART_BUFFER usart3_it_TXbuffer;
     extern volatile SERIAL_USART_BUFFER usart3_it_RXbuffer;
diff --git a/inc/config.h b/inc/config.h
index b9ba67f..b018079 100644
--- a/inc/config.h
+++ b/inc/config.h
@@ -16,7 +16,7 @@
   #define HOVERBOARD_WITH_SOFTWARE_SERIAL_B2_C9_6WORDSENSOR 5
 
   // thoery says this is the only thing you need to change....
-  #define CONTROL_TYPE HOVERBOARD_WITH_SOFTWARE_SERIAL_B2_C9
+  #define CONTROL_TYPE USART2_CONTROLLED
   //////////////////////////////////////////////////////////
 
   //////////////////////////////////////////////////////////
@@ -261,12 +261,12 @@
 #endif
 
 #ifndef INACTIVITY_TIMEOUT
-  #define INACTIVITY_TIMEOUT 8        // minutes of not driving until poweroff. it is not very precise.
+  #define INACTIVITY_TIMEOUT 16        // minutes of not driving until poweroff. it is not very precise.
 #endif
 
 // ############################### SERIAL DEBUG ###############################
 
-//#define DEBUG_SERIAL_USART3         // right sensor board cable, disable if I2C (nunchuk) is used!
+#define DEBUG_SERIAL_USART3         // right sensor board cable, disable if I2C (nunchuk) is used!
 //#define DEBUG_SERIAL_SENSOR         // send to USART3 sensor board, without framing, at the CONTROL_SENSOR_BAUD rate
 //#define DEBUG_SERIAL_SERVOTERM
 //#define DEBUG_SERIAL_ASCII          // "1:345 2:1337 3:0 4:0 5:0 6:0 7:0 8:0\r\n"
diff --git a/platformio.ini b/platformio.ini
index 855d598..8a3118b 100644
--- a/platformio.ini
+++ b/platformio.ini
@@ -4,11 +4,11 @@
 [platformio]
 include_dir = inc
 
-env_default = genericSTM32F103RC
+;env_default = genericSTM32F103RC
 ;env_default = hoverboard
 ;env_default = hoverboard_6word
 ;env_default = control_softwareserial
-;env_default = control_usart2
+env_default = control_usart2
 ;env_default = control_usart3
 ;env_default = control_usart3_ADC
 
diff --git a/src/comms.c b/src/comms.c
index 47585b3..1062a04 100644
--- a/src/comms.c
+++ b/src/comms.c
@@ -28,7 +28,7 @@ volatile int16_t ch_buf[8];
   volatile SERIAL_USART_BUFFER usart2_it_TXbuffer;
   volatile SERIAL_USART_BUFFER usart2_it_RXbuffer;
 #endif
-#if defined(SERIAL_USART3_IT)
+#if defined(SERIAL_USART3_IT) || defined(DEBUG_SERIAL_USART3)
   volatile SERIAL_USART_BUFFER usart3_it_TXbuffer;
   volatile SERIAL_USART_BUFFER usart3_it_RXbuffer;
 #endif
@@ -107,9 +107,9 @@ void consoleLog(char *message)
     USART_sensorSend(1, (unsigned char *)message, strlen(message), 0);
     #else
       // TODO: Method to select which input is used for Protocol when both are active
-      #if defined(SERIAL_USART2_IT) && !defined(READ_SENSOR)
+      #if defined(DEBUG_SERIAL_USART2) && !defined(READ_SENSOR)
         USART2_IT_send((unsigned char *)message, strlen(message));
-      #elif defined(SERIAL_USART3_IT) && !defined(READ_SENSOR)
+      #elif defined(DEBUG_SERIAL_USART3) && !defined(READ_SENSOR)
         USART3_IT_send((unsigned char *)message, strlen(message));
       #elif !defined(READ_SENSOR) && defined(DEBUG_SERIAL_SENSOR)
         HAL_UART_Transmit_DMA(&huart2, (uint8_t *)message, strlen(message));
@@ -167,7 +167,7 @@ void USART2_IT_IRQ(USART_TypeDef *us) {
 
 #endif
 
-#ifdef SERIAL_USART3_IT
+#if defined(SERIAL_USART3_IT) || defined(DEBUG_SERIAL_USART3)
 
 int USART3_IT_starttx() {
     __HAL_UART_ENABLE_IT(&huart3, UART_IT_TXE);
diff --git a/src/setup.c b/src/setup.c
index fb3ffe7..279225b 100644
--- a/src/setup.c
+++ b/src/setup.c
@@ -78,7 +78,7 @@ void UART_Init() {
 
   UART_HandleTypeDef huart3;
   huart3.Instance          = USART3;
-  huart3.Init.BaudRate     = DEBUG_BAUD;
+  huart3.Init.BaudRate     = 115200;
   huart3.Init.WordLength   = UART_WORDLENGTH_8B;
   huart3.Init.StopBits     = UART_STOPBITS_1;
   huart3.Init.Parity       = UART_PARITY_NONE;

```

**Comment by quangvu16** [comment]
Dear Alex,
Thank you for your help. Please help us again.
After uploaded your firmware is based on commit 5d296378f30891fdbd40b45df61b52666f4f4cdc from https://github.com/bipropellant/bipropellant-hoverboard-firmware/commits, we can control motor by:
ubuntu@ubuntu:~/Ros_ws$ rosrun teleop_twist_keyboard teleop_twist_keyboard.py cmd_vel:=/hoverboard_velocity_controller/cmd_vel
ubuntu@ubuntu:~/Ros_ws$ rostopipub /hoverboard_velocity_controller/cmd_vel geometry_msgs/Twist -r 3 -- '[6, 0.0, 0.0]' '[0.0, 0.0, 0]'
However, only left motor runs, right motor stop.
https://youtu.be/Qqt9yTYJDnk
Please help us solve this issue.
Best regardss,

**Comment by busbuyukefe** [comment]
We are using this firmware, I compiled it from the commit you mentioned with only usart2 enabled.
https://gist.github.com/busbuyukefe/0230aedd1c5914bc7cdb11fb24a967c8

**Comment by quangvu16** [comment]
We solved this issue.
https://github.com/alex-makarov/hoverboard-driver/issues/5

**Comment by Andyzug** [comment]
Hey @quangvu16 can you please describe step by step what you did to solve "just one wheel runs"?
it's confusing for me on #5

**Comment by quangvu16** [comment]
You can use hoverboard-driver of @elector102
https://github.com/elector102/hoverboard-driver/tree/test_comunicaiton

Step 1: git clone https://github.com/elector102/hoverboard-driver.git
Step 2: cd hoverboard-driver
Step 3: git checkout test_comunicaiton
Step 4: git submodule update --init --recursive
(*) you have to register key and your email on github.

**Comment by Andyzug** [comment]
@quangvu16 Thank you!
 Now it works, I had to change PORT in "catkin_ws/src/hoverboard-driver/include/hoverboard_driver/config.h" with #define PORT "/dev/ttyTHS1"
And used this Firmware https://gist.github.com/busbuyukefe/0230aedd1c5914bc7cdb11fb24a967c8
huh... a long journey till here, still a lot to go :D

**Comment by quangvu16** [comment]
Installation Steps:  
https://github.com/quangvu16/hoverboard_driver
