### ISSUE TITLE
How to send cmd_vel commands

### ISSUE THREAD

**Issue by MartinNievas** [alex-makarov/hoverboard-driver#14]
Hi, first of all, thanks for sharing the project

I could not make it work, my setup is:

  - ROS melodic
  - A hoverboard with bipropellant firmware

Steps:

1. Flashed a hoverboard with the latest [bipropellant firmware](https://github.com/bipropellant/bipropellant-hoverboard-firmware). An adjusted [some configurations](https://github.com/MartinNievas/bipropellant-hoverboard-firmware/commit/e899d8517c173ef8af47b120c5cd9e731c69ce9a) for the battery.
2. Compile the latest version of [hoverboard-driver](https://github.com/alex-makarov/hoverboard-driver/tree/master) through `catkin make` without errors.
Changed `PORT` in `include/hoverboard_driver/config.h` with my USB-uart adapter id.
3. Run the code through:
```bash
$ roslaunch hoverboard_driver hoverboard.launch
```
4. Open a new terminal and send velocity commands with:
```bash
$ rosrun teleop_twist_keyboard teleop_twist_keyboard.py cmd_vel:=/hoverboard_velocity_controller/cmd_vel
```

But I don't get any movement on the wheels.

I also tried these configurations:

1. Not worked
- bipropellant-hoverboard-firmware [latest]
- hoveboard-driver in [this commit](https://github.com/alex-makarov/hoverboard-driver/commit/5713aefbfacafecc901e9be7c3e653ff0bc34edc)

2. Not worked
- bipropellant-hoverboard-firmware [latest]
- hoveboard-driver in [this commit](https://github.com/alex-makarov/hoverboard-driver/commit/8d5c7ef5aaf986842c08e3041141c18406006241)

I can run bipropellant-hoverboard-firmware with `DEBUG_SERIAL_ASCII` and I can send manual PWM command to the hoverboard, and the wheels start to spinning. 

Is there is something that I missed? Thanks

**Comment by Andyzug** [comment]
Hi!
Try to follow these steps: https://github.com/alex-makarov/hoverboard-driver/issues/13#issuecomment-803681694
and this firmware: https://gist.github.com/busbuyukefe/0230aedd1c5914bc7cdb11fb24a967c8

**Comment by MartinNievas** [comment]
@Andyzug steps in https://github.com/alex-makarov/hoverboard-driver/issues/13#issuecomment-803681694 worked perfectly.

I didn't realize that [hbprotocol](https://github.com/alex-makarov/bipropellant-protocol/tree/9383e495c65978f02e11a51c41db39d4ee1d91d2) is a submodule in the [bipropellant-hoverboard-firmware](https://github.com/bipropellant/bipropellant-hoverboard-firmware) that need's to match with the submodule used in [hoverboard-driver](https://github.com/alex-makarov/hoverboard-driver). So, after pointing `hbprotocol` to the same version in both repositories, I can send cmd_vel commands and both wheels are spinning.

Thanks for the binary. But because I have to modify the original code of the hoverboard, I need to compile it from the repository.

Thanks a lot! :D
