### ISSUE TITLE
Ros2 update

### ISSUE THREAD

**Issue by Dhruti1994** [alex-makarov/hoverboard-driver#24]
Please , if possible update the whole library for ROS2 as well.

**Comment by AlfreddGco** [comment]
I'm on it. But because of my OS, will probably be an update for foxy (from there, should be easier to update to humble)

**Comment by tomy983** [comment]
Hi @AlfreddGco, do you plan to issue a pr for the ros2 version?

**Comment by AlfreddGco** [comment]
Had forgotten about it since my team decided to use ROS1 for the project, but I already have most of the work done. Will try to make a PR by January 4th (it's on my calendar now)

**Comment by AlfreddGco** [comment]
For some reason my reminder didn't worked and sent me a notification but I just made the repository public while I make a PR.

There's also a very useful utility in the codebase in which you can emulate a serial connection without the need of hardware. Honestly the version for ROS2 is not totally tested and neither probably well built but I think that there's at least a lot of work already done.

As long as I remember the main branch is for foxy and the humble branch is (obviously) for humble.

Here's the link to the adapted repo: https://github.com/AlfreddGco/sonnybot-agv/tree/main/src/hoverboard-driver

PS: I wouldn't be bothered if someone else does the PR using the code that I changed before I manage to do submit it.

**Comment by tomy983** [comment]
Thank you @AlfreddGco, as soon as I will try it, I will let you know how it works!

**Comment by quangvu16** [comment]
Did you try this driver fro ros2: https://github.com/victorfdezc/ros2-hoverboard-driver?

**Comment by PedroKay** [comment]
Not yet, thanks for the heads up!

**Comment by PaddyCube** [comment]
For those of you looking for a ROS2 version. I build one which runs fine on ROS2 Humble. Have a look at the humble branch
https://github.com/hoverboard-robotics/hoverboard-driver/tree/humble

**Comment by ImperiumKontratakuje** [comment]
What a **great** news! I have been waiting for this moment for quite a long time. All my previous projects utilized ROS1 (Noetic Ninjemys) and I really missed having a driver for ROS2. This opens the door for new explorations and many new possibilities (DDS, RFM, QoS) :) Thank you on behalf of myself and my robots :)

![2023-10-Konrad-Dudziak-hoverboard-robaka](https://github.com/hoverboard-robotics/hoverboard-driver/assets/85103771/3ad4031f-20c7-4103-92ed-380b11450719)
