### ISSUE TITLE
Error during communications.

### ISSUE THREAD

**Issue by elector102** [alex-makarov/hoverboard-driver#3]
First, it is a great project! and congrats! a great job!. I ham having problems while I am trying to read the serial communication, using your node, one thing that I realize is that this node has a different version of hbprotocol, I am using [this repo](https://github.com/bipropellant/bipropellant-hoverboard-firmware) that have the version hbprotocol @ 6f9d1bd, and your repo uses that version: bipropellant @ 38f9384. it could cause some issues? in advantage! thank you very much.

**Comment by elector102** [comment]
I am sure that tI am doing something wrong, if I try to make it work like original, I have this [line](https://github.com/alex-makarov/bipropellant-hoverboard-api/blob/38f9384b7f0eb0079ff13d76856c4772fd20fa6d/src/HoverboardAPI.h#L4). That when I tried to compile, it fails. it is because it is an Arduino library and the compiler can't found it(catkin)

**Comment by alex-makarov** [comment]
Hey @elector102 , I believe when you clone the repo with subfolders
```
git clone --recurse-submodules git@github.com:alex-makarov/hoverboard-driver.git
``` 
you should get the right version of the protocol cloned with it.

**Comment by elector102** [comment]
Yes, I am doing that, exactly how do you say:
![Screenshot from 2020-03-31 09-37-54](https://user-images.githubusercontent.com/5404364/78029671-5da96700-7337-11ea-9392-493374931c34.png)

And when I tried to compile I have the following:
![Screenshot from 2020-03-31 09-38-45](https://user-images.githubusercontent.com/5404364/78029761-79ad0880-7337-11ea-9bbb-e6250202e063.png)

that is weird because it is asking for an Arduino library.

**Comment by alex-makarov** [comment]
@elector102 You are right, the submodule was pointing to the wrong commit. Fixed it, please pull and rebuild.

**Comment by elector102** [comment]
Thanks, now it works!! sorry for the delay, I burned some boards in the middle, haha. Clearly, I am doing something wrong, I am loading this firmware to the board and trying to connect to any of the serial port(left sensor board and right sensor board). but I don't have any responses, Just in case, I am only downloading the firmware and flashing the hoverboard, without any modification. where is the default serial port of this board, and the speed is at 115200? sorry for this questions.

**Comment by alex-makarov** [comment]
Hey @elector102 , if I remember correctly I'm using the default config with the only setting:
> +  #define CONTROL_TYPE USART2_CONTROLLED

**Comment by elector102** [comment]
Great! thanks, @alex-makarov ! yea, you need to upload the firmware using an environment variable during the compilation to select the serial communication. I hope in the future collaborate with your project.
