### ISSUE TITLE
Connections and PID

### ISSUE THREAD

**Issue by bekirbostanci** [alex-makarov/hoverboard-driver#7]
Hi
How can i connect arduino and hoverboard mainboard or nano and hoverboard mainboard. Which port should I use? 
Also did you have any problem about the motor controls. Do the motors work correctly? or is it necessary to use a pid?
for example rotating at equal speeds

Thank you for answers

**Comment by alex-makarov** [comment]
Hey,

I'm using USART2.

Motors work correctly without PID control (at least with no load), but then your changes are instant -- not something you want for a mobile platform. I don't see any reason to avoid using PID, it helps a lot in fine tuning the motion.

**Comment by bekirbostanci** [comment]
thank you for answer but I wanted to learn, there are 2 different tx rx pins on the mainboard, I don't know which one to use. I couldn't see a diagram about it either. thank you so much for your answer again

**Comment by alex-makarov** [comment]
Check the firmware repo, it has a picture -- https://github.com/bipropellant/bipropellant-hoverboard-firmware
USART2 is on the left.

**Comment by bekirbostanci** [comment]
thank you again for answers
