### ISSUE TITLE
Is this package compatible with Raspberry pi 4?

### ISSUE THREAD

**Issue by numan1702** [alex-makarov/hoverboard-driver#9]
I used this package on ROS Melodic Devel with bipropellant-hoverboard-firmware, I used Rasberry pi 4 8gb. On the Raspi board architecture there is only 1 uart port.
Can I use it with only 1 left sensor port and connect it to the Raspi board ?
Is the j44 UART port on your Jetson nano board connected to the right sensor port as STM debug ?

**Comment by elector102** [comment]
Yes! you only need one uart port. you can found a bit of information here: https://github.com/bipropellant/bipropellant-hoverboard-firmware. Just in case

**Comment by quangvu16** [comment]
Dear @elector102 
As I know, you compile successfully Alex's ros package. Please send me firmware hex file of hoverboard if you still keep it.
My email: vuvuvu@outlook.com
Thank you,
